CC = gcc

task_1: task_1.c
	$(CC) $<
	./a.out

task_2: task_2.c
	$(CC) $<
	./a.out

task_3: task_3.c area.c movement.c
	$(CC) area.c -o area.exe -lm
	$(CC) movement.c -o movement.exe -lm
	$(CC) $<
	./a.out

task_4: task_4.c
	$(CC) $<
	./a.out

task_5: task_5.c
	$(CC) $<
	./a.out