/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/sem.h>
#include <sys/stat.h>
#include <unistd.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int semid;

pthread_t p_thread;
pthread_attr_t attr;

struct thr_data
{
    struct svc_req *rqstp;
    SVCXPRT *transp;
};

/* Процедура выполняемая потоком */ 
void* serv_request(void *data)
{
	struct thr_data *ptr_data;

	union {
		int service_1_arg;
	} argument;

	union {
		char service_1_res;
	} result;

	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

    ptr_data = (struct thr_data  *)data;
    struct svc_req *rqstp = ptr_data->rqstp;
    register SVCXPRT *transp = ptr_data->transp;

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		pthread_exit(0);

	case SERVICE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))service_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		pthread_exit(0);
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		pthread_exit(0);
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!pc_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	pthread_exit(0);
}

/*
   Принципиально измененный код процедуры pc_prog_1,
   стартующей поток для каждого клиентского запроса
   на запуск удаленной процедуры
 */
static void pc_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	struct thr_data *data_ptr = (struct thr_data*) malloc(sizeof(struct thr_data));
    data_ptr->rqstp = rqstp;
    data_ptr->transp = transp;
    pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
    if(pthread_create(&p_thread, &attr, serv_request, (void *)data_ptr) != 0) {
        perror("Error: create thread");
        exit(1);
   }
}


int main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PC_PROG, PC_VER);

	// Инициализация семафоров
    key_t semkey = ftok("file.txt", 4);
    if (semkey == (key_t)-1)
    {
        perror("Error: ftok\n");
        exit(1);
    }
    semid = semget(semkey, 3, IPC_CREAT | 0666);
    if (semid == -1)
    {
        perror("Error: semget\n");
        exit(1);
    }
    // Функция semctl() позволяет изменять управляющие параметры набора семафоров
	if (semctl(semid, BIN_SEM, SETVAL, 1) == -1)
    {
        perror("Error: semctl (BIN_SEM).\n");
        exit(1);
    }
    if (semctl(semid, BUFF_EMPTY, SETVAL, SIZE_BUF) == -1)
    {
        perror("Error: semctl (BUFF_EMPTY).\n");
        exit(1);
    }
    if  (semctl(semid, BUFF_FULL, SETVAL, 0) == -1)
    {
        perror("Error: semctl (BUFF_FULL).\n");
        exit(1);
    }

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PC_PROG, PC_VER, pc_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PC_PROG, PC_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PC_PROG, PC_VER, pc_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PC_PROG, PC_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
