/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"

#define SIZE_BUF 26

static char** addr_prod = &addr;
static char** addr_cons = &addr;
static char letter = 'a';

char producer(void)
{
	char result = letter;
	**addr_prod = letter;
	printf("Producer -> %c\n", **addr_prod);
    if (**addr_prod == 'z')
    {
        *addr_prod -= SIZE_BUF;
        letter = 'a';
    }
    else
    {
        (*addr_prod)++;
        letter++;
    }
	return result;
}

char consumer(void)
{
	char result = letter;
	**addr_cons = letter;
	printf("Consumer -> %c\n", **addr_cons);
    if (**addr_cons == 'z')
        *addr_cons -= SIZE_BUF;
    else
        (*addr_cons)++;
	return result;
}

bool_t
service_1_svc(struct PROD_CONS *argp, struct PROD_CONS *result, struct svc_req *rqstp)
{
	bool_t retval;

	if (argp->type == 0)
		(*result).result = producer();
	else
		(*result).result = consumer();

	return retval;
}

int
pc_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	free(addr);

	return 1;
}
