/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include "pc.h"


void
pc_prog_1(char *host, int role)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct PROD_CONS result_1;
	struct PROD_CONS  service_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	struct timeval timeout;
	timeout.tv_sec = 60; // Таймаут 60 секунд
	timeout.tv_usec = 0;

	if (!clnt_control(clnt, CLSET_TIMEOUT, (char *)&timeout)) {
		fprintf(stderr, "Failed to set timeout\n");
		exit(1);
	}
#endif	/* DEBUG */

	service_1_arg.type = role;

	while (1)
	{
		sleep(rand() % 5 + 1);

        retval_1 = service_1(&service_1_arg, &result_1, clnt);
        if (retval_1 != RPC_SUCCESS)
            clnt_perror(clnt, "call failed");
        else
            printf("type = %d, result = %c\n", role, result_1.result);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int role;

	if (argc < 3) {
		printf ("usage: %s server_host role\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	role = atoi(argv[2]);

    if (role != 0 && role != 1) {
        printf("role must be 0 or 1\n");
        exit(1);
    }

    srand(time(NULL));

    pc_prog_1(host, role);
exit (0);
}
