/*                       Modified pc_svc.c (multithreaded version)
 *               
 * Please do not edit this file directly.
 * It was modified from the original code generated using rpcgen.
 */

#include "pc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h>
#include <sys/sem.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_t p_thread;
pthread_attr_t attr;

/* Thread procedure for handling requests */ 
void *
serv_request(void *data)
{
    struct thr_data
    {
        struct svc_req *rqstp;
        SVCXPRT *transp;
    } *ptr_data;

    ptr_data = (struct thr_data *)data;
    struct svc_req *rqstp = ptr_data->rqstp;
    register SVCXPRT *transp = ptr_data->transp;

    union {
        int service_1_arg;
    } argument;
    union {
        char *service_1_res;
    } result;

    bool_t retval;
    xdrproc_t _xdr_argument, _xdr_result;
    bool_t (*local)(char *, void *, struct svc_req *);

    switch (rqstp->rq_proc) {
        case NULLPROC:
            (void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
            pthread_exit(0);

        case SERVICE:
            _xdr_argument = (xdrproc_t) xdr_int;
            _xdr_result = (xdrproc_t) xdr_wrapstring;
            local = (bool_t (*) (char *, void *, struct svc_req *))service_1_svc;
            break;

        default:
            svcerr_noproc(transp);
            pthread_exit(0);
    }

    memset((char *)&argument, 0, sizeof(argument));
    if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
        svcerr_decode(transp);
        pthread_exit(0);
    }

    retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
    if (retval > 0 && !svc_sendreply(transp, _xdr_result, (char *)&result)) {
        svcerr_systemerr(transp);
    }
    if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
        fprintf(stderr, "%s", "unable to free arguments");
        exit(1);
    }
    if (!pc_prog_1_freeresult(transp, _xdr_result, (caddr_t) &result))
        fprintf(stderr, "%s", "unable to free results");

    pthread_exit(0);
}

/* Main dispatcher function, starts a thread for each request */
static void pc_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
    struct data_str
    {
        struct svc_req *rqstp;
        SVCXPRT *transp;
    } *data_ptr = (struct data_str *)malloc(sizeof(struct data_str));

    data_ptr->rqstp = rqstp;
    data_ptr->transp = transp;

    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_create(&p_thread, &attr, serv_request, (void *)data_ptr);
}

int main(int argc, char **argv)
{
    register SVCXPRT *transp;

    pmap_unset(PC_PROG, PC_VER);

    transp = svcudp_create(RPC_ANYSOCK);
    if (transp == NULL) {
        fprintf(stderr, "%s", "cannot create UDP service.");
        exit(1);
    }
    if (!svc_register(transp, PC_PROG, PC_VER, pc_prog_1, IPPROTO_UDP)) {
        fprintf(stderr, "%s", "unable to register (PC_PROG, PC_VER, UDP).");
        exit(1);
    }

    transp = svctcp_create(RPC_ANYSOCK, 0, 0);
    if (transp == NULL) {
        fprintf(stderr, "%s", "cannot create TCP service.");
        exit(1);
    }
    if (!svc_register(transp, PC_PROG, PC_VER, pc_prog_1, IPPROTO_TCP)) {
        fprintf(stderr, "%s", "unable to register (PC_PROG, PC_VER, TCP).");
        exit(1);
    }

    svc_run();
    fprintf(stderr, "%s", "svc_run returned");
    exit(1);
    /* NOTREACHED */
}