/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#define CLIENTS_COUNT 5


void bakery_prog_1(char *host)
{
	CLIENT *clnt;
	struct REQUEST  *result_1;
	struct REQUEST request;
    request.pid = getpid();
	float  *result_2;

#ifndef	DEBUG
	clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "tcp");
	if (clnt == NULL)
	{
		clnt_pcreateerror (host);
		exit (1);
	}
	struct timeval timeout;
	timeout.tv_sec = 20; // Таймаут 20 секунд
	timeout.tv_usec = 0;

	if (!clnt_control(clnt, CLSET_TIMEOUT, (char *)&timeout)) {
		fprintf(stderr, "Failed to set timeout\n");
		exit(1);
	}
#endif	/* DEBUG */

	srand(time(NULL) ^ getpid());
    usleep(rand() % 1000000 + 1000000);

	result_1 = get_number_1(&request, clnt);
	if (result_1 == (struct REQUEST *) NULL)
		clnt_perror (clnt, "call failed");

	request.index = result_1->index;
    request.number = result_1->number;

	printf("Client (pid: %d) receive number: %d\n", request.pid, request.number);

    usleep(rand() % 1000000 + 1000000);

	request.op = rand() % 4;
    request.arg1 = rand() % 1000 + 1;
    request.arg2 = rand() % 900 + 1;

	result_2 = bakery_service_1(&request, clnt);
	if (result_2 == (float *) NULL)
		clnt_perror (clnt, "call failed");

	char c_op = '!';
    switch (request.op)
	{
    case ADD:
        c_op = '+';
        break;
    case SUB:
        c_op = '-';
        break;
    case MUL:
        c_op = '*';
        break;
    case DIV:
        c_op = '/';
        break;
    default:
        break;
    }

    printf("Client with number %d (pid: %d): %.2f %c %.2f = %.2f\n", request.number, request.pid, request.arg1, c_op, request.arg2, *result_2);

#ifndef	DEBUG
	clnt_destroy(clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	pid_t client_pid[CLIENTS_COUNT];

	for (size_t i = 0; i < CLIENTS_COUNT; i++)
	{
		if ((client_pid[i] = fork()) == -1)
		{
			perror("Can't fork\n");
			exit(1);
		}
		else if (client_pid[i] == 0)
		{
			bakery_prog_1(host);
			return 0;
		}
	}

	for (size_t i = 0; i < CLIENTS_COUNT; i++)
	{
		int status;
		waitpid(client_pid[i], &status, 0);
	}

	printf("Parent client exited\n");

	exit (0);
}
