/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>

#define MAX_CLIENTS 512

static int numbers[MAX_CLIENTS] = { false };


int *
get_number_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	for (int i = 1; i < MAX_CLIENTS; i++)
        if (numbers[i])
            result = i;
    result++;
    numbers[result] = true;

    printf("Client receive number %d\n",  result);

	return &result;
}

float *
bakery_service_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
	static float  result;

	int cur_num = argp->number;
	for (int i = 0; i < cur_num; i++)
        while (numbers[i] != false);

    // вычисление выражения
    int c_op;
    switch (argp->op)
    {
    case ADD:
        result = argp->arg1 + argp->arg2;
        c_op = '+';
        break;
    case SUB:
        result = argp->arg1 - argp->arg2;
        c_op = '-';
        break;
    case MUL:
        result = argp->arg1 * argp->arg2;
        c_op = '*';
        break;
    default:
        result = argp->arg1 / argp->arg2;
        c_op = '/';
    }

    numbers[cur_num] = false;

    printf("Client with number %d: %.2f %c %.2f = %.2f\n", argp->number, argp->arg1, c_op, argp->arg2, result);

	return &result;
}
