/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct REQUEST {
	int index;
	int number;
	int pid;
	int op;
	float arg1;
	float arg2;
	float result;
};
typedef struct REQUEST REQUEST;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 2

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUMBER 1
extern  struct REQUEST * get_number_2(struct REQUEST *, CLIENT *);
extern  struct REQUEST * get_number_2_svc(struct REQUEST *, struct svc_req *);
#define BAKERY_SERVICE 2
extern  float * bakery_service_2(struct REQUEST *, CLIENT *);
extern  float * bakery_service_2_svc(struct REQUEST *, struct svc_req *);
extern int bakery_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUMBER 1
extern  struct REQUEST * get_number_2();
extern  struct REQUEST * get_number_2_svc();
#define BAKERY_SERVICE 2
extern  float * bakery_service_2();
extern  float * bakery_service_2_svc();
extern int bakery_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_REQUEST (XDR *, REQUEST*);

#else /* K&R C */
extern bool_t xdr_REQUEST ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
