/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PC_H_RPCGEN
#define _PC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

// семафоры
#define BIN_SEM 0
#define BUFF_FULL 1
#define BUFF_EMPTY 2
#define SIZE_BUF 26
extern int semid;


struct PROD_CONS {
	int type;
	char result;
};
typedef struct PROD_CONS PROD_CONS;

#define PC_PROG 0x20000001
#define PC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SERVICE 1
extern  enum clnt_stat service_1(struct PROD_CONS *, struct PROD_CONS *, CLIENT *);
extern  bool_t service_1_svc(struct PROD_CONS *, struct PROD_CONS *, struct svc_req *);
extern int pc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SERVICE 1
extern  enum clnt_stat service_1();
extern  bool_t service_1_svc();
extern int pc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PROD_CONS (XDR *, PROD_CONS*);

#else /* K&R C */
extern bool_t xdr_PROD_CONS ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PC_H_RPCGEN */
