/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pc.h"

bool_t
xdr_PROD_CONS (XDR *xdrs, PROD_CONS *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
